### ISSUE TITLE
Add LinkField to our Cuccumber Studio test suite

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#225] opened 2024-02-15 04:44 UTC
As the product owner of Silverstripe CMS, I want assurance that LinkField is regularly tested to minimise the risk of regression.

### For testing team
- [x] The following test cases are covered in by our cucumber studio suite
- [x] A sandbox is deployed with the test module and the testing team is granted access.
- [x] Both regular page forms and elemental block forms are tested.
- [x] Test are written with the expectation of "least privileged".
#### Page
  - [x] Creating/updating/publishing/archiving a link in single LinkField
  - [x] Creating/updating/publishing/archiving links in MultiLinkField
  - [x] Reordering a link list
  - [x] Editing each link types
  - [x] Rendering link in the front end
  - [x] Trying to edit a link you don't have access to.
#### DataObject / Elemental
  - [x] Integration of the linkfield with other DataObject
    - [x] Cover required LinkField
    - [x] Cover draft states
    - [x] Cover link with no link text

### For CMS Squad
- [x] Our default testing module ships whit a page type and an elemental block that covers all the scenarios above.
- [x] All the LinkField are rendered on the front end.

## PRs
- https://github.com/silverstripe/recipe-kitchen-sink/pull/56
- https://github.com/silverstripeltd/cms-testing-recipes/pull/5
- https://github.com/silverstripe/silverstripe-frameworktest/pull/167

**Comment by maxime-rainville** [comment] 2024-02-22 22:25
Note to self:
- Need to add some screen shot
- Need to set up some a sandbox to play with it.
- Point to userhelp.

**Comment by emteknetnz** [comment] 2024-02-29 02:13
@sabina-talipova Not sure why you've assigned to me to peer review, there are no remaining pull-requests though we still need cucumber studio tests written by someone

**Comment by sabina-talipova** [comment] 2024-03-01 00:33
Move to "Awaiting" column. I will discuss next week with the testing team how it will be more convenient and easier to create new test cases in Cucumber Studio. Since the testing team does not have much experience working with Cucumber Studio and is not very aware of the approaches that our team uses when organizing a project and adding new test cases and steps.

**Comment by sabina-talipova** [comment] 2024-03-14 20:11
Test cases in Cucumber Studio is ready: https://studio.cucumber.io/projects/301855/test-plan/folders/3737084
Test cases have been tested as part of 5.2.0-beta1 regression testing.
Close this ticket as completed.

**Closed as completed by sabina-talipova** 2024-03-14 20:11 UTC
Labels: type/other
