### ISSUE TITLE
LinkField support for has_many

### ISSUE THREAD

**Issue by mfendeksilverstripe** [silverstripe/silverstripe-linkfield#44] opened 2022-05-13 00:25 UTC
# LinkField support for has_many

Current React UI only supports `has_one` relationship for `Link` via the `LinkField`. We need to enhance this field to handle `has_many` relationship as well to enhance the CMS user experience.

## Setup

Added a simple `has_many` relationship.

`CtaBlock.php`:
```php
private static array $has_many = [
    'Links' => Link::class,
];
```

`LinkRelationExtension.php`:
```php
private static array $has_one = [
    'CtaBlock' => CtaBlock::class,
];
```

## Current state

We have to rely on `GridField` to manage these links as `LinkField` doesn't support this relationship setup. This functionally works but is far from ideal.

## Desired state

The goal is the use LinkField with the `Links` relation in a similar way we can use `UploadField` to handle a `has_many` relation. We expect a React UI to be available to allow content author to manage multiple links via this field.

## Impacted versions

This feature can be implemented only in GraphQL 4 compatible version as this is an enhancements. Back-porting this to the GraphQL 3 compatible is a nice to have but not manadatory.

## Pull request
- [ ] #45

**Comment by maxime-rainville** [comment] 2023-11-23 04:48
Duplicate of https://github.com/silverstripe/silverstripe-linkfield/issues/107

**Closed by maxime-rainville** 2023-11-23 04:48 UTC
Labels: type/enhancement, type/UX
