### ISSUE TITLE
Component does not render correctly on existing links where Link canCreate fails or is not an allowed type

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-linkfield#178] opened 2024-01-18 05:02 UTC
If there is an existing link where MyLinkType::canCreate() fails then the icon will not render, nor will the type text e.g. "Phone number"

![image](https://github.com/silverstripe/silverstripe-linkfield/assets/4809037/395b8afd-4e62-41c9-bfb2-9f79e87154d5)

This also happens if `->setAllowedTypes([SomeOtherLinkType::class])` is called without including MyLinkType::class

**Comment by sabina-talipova** [comment] 2024-01-18 19:59
I've already fixed it here: https://github.com/silverstripe/silverstripe-linkfield/issues/176

**Comment by GuySartorelli** [comment] 2024-01-18 20:10
Closing as duplicate of https://github.com/silverstripe/silverstripe-linkfield/issues/176

**Closed as completed by GuySartorelli** 2024-01-18 20:10 UTC
