### ISSUE TITLE
Page save/publish buttons can reflect a dirty link state

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-linkfield#96] opened 2023-09-28 05:21 UTC
## Story
As a content author I want to know when I have outstanding change my link field.

## Notes
- Dirty link state (i.e. draft or modified) probably won't be handled on page reload - see https://github.com/silverstripe/silverstripe-admin/issues/1593
- This is possibly a duplicate of https://github.com/silverstripe/silverstripe-linkfield/issues/152

## Acceptance criteria
- ~~LinkField provides visual indication when outstanding changes in the field need to be change~~ already done
- Save/Publish button accounts for the dirty state (i.e. draft/modified states should affect the save/publish buttons)
- Dirty state considers any sorting update
- Works correctly for versioned *and* unversioned link models

**Comment by GuySartorelli** [comment] 2024-01-15 03:02
Done already, and duplicate

**Comment by GuySartorelli** [comment] 2024-01-16 20:37
Just realised this talks about the save/publish buttons, which have not yet been handled. Reopening

**Comment by emteknetnz** [comment] 2024-01-29 21:34
This is a duplicate of https://github.com/silverstripe/silverstripe-linkfield/issues/152

**Closed as completed** 2024-01-29 22:14 UTC
Labels: affects/v5, complexity/low, impact/low, type/enhancement, type/UX
